import Link from 'next/link';
import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { ArrowRight } from 'lucide-react';
import { getBlogPost, getBlogList, renderMarkdownWithToc, extractFaq } from '@/lib/blog';
import { relatedRefsForArticle } from '@/lib/related-refs';

export const revalidate = 60;

const SITE = 'https://seosnapshot.dev';

export async function generateMetadata({ params }: { params: { slug: string } }): Promise<Metadata> {
  const post = await getBlogPost(params.slug);
  if (!post) return { title: 'Article not found' };
  const description = post.excerpt || `${post.title} — a practical SEO guide from SEO Snapshot.`;
  const url = `${SITE}/blog/${post.slug}`;
  return {
    title: post.title,
    description,
    alternates: { canonical: url },
    openGraph: {
      type: 'article',
      title: post.title,
      description,
      url,
      publishedTime: post.date || undefined,
      // Image supplied by the file-based `opengraph-image.tsx` (dynamic PNG).
    },
    twitter: { card: 'summary_large_image', title: post.title, description },
  };
}

export default async function BlogPost({ params }: { params: { slug: string } }) {
  const post = await getBlogPost(params.slug);
  if (!post) notFound();

  const { html, toc } = renderMarkdownWithToc(post.content);
  const related = (await getBlogList()).filter((p) => p.slug !== post.slug).slice(0, 3);
  const refs = relatedRefsForArticle(post.slug);
  const url = `${SITE}/blog/${post.slug}`;
  const wordCount = post.content.trim().split(/\s+/).length;
  const readTime = Math.max(1, Math.round(wordCount / 200));

  const articleLd = {
    '@context': 'https://schema.org',
    '@type': 'Article',
    headline: post.title,
    description: post.excerpt || undefined,
    // Raster PNG generated by the file-based opengraph-image route (Article schema wants a raster image).
    image: `${SITE}/blog/${post.slug}/opengraph-image`,
    datePublished: post.date || undefined,
    dateModified: post.date || undefined,
    wordCount,
    inLanguage: 'en',
    mainEntityOfPage: { '@type': 'WebPage', '@id': url },
    author: { '@type': 'Organization', name: 'SEO Snapshot', url: SITE },
    publisher: { '@type': 'Organization', name: 'SEO Snapshot', url: SITE, logo: { '@type': 'ImageObject', url: `${SITE}/favicon.svg` } },
  };
  const breadcrumbLd = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: 'Home', item: SITE },
      { '@type': 'ListItem', position: 2, name: 'Blog', item: `${SITE}/blog` },
      { '@type': 'ListItem', position: 3, name: post.title, item: url },
    ],
  };
  // FAQPage schema — makes the article eligible for FAQ rich results when it
  // has a `## FAQ` section. Google wants Q&A that's visible on the page, which
  // these are (rendered in the article body below).
  const faqs = extractFaq(post.content);
  const faqLd = faqs.length > 0 ? {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: faqs.map((f) => ({
      '@type': 'Question',
      name: f.question,
      acceptedAnswer: { '@type': 'Answer', text: f.answer },
    })),
  } : null;
  const prettyDate = post.date
    ? new Date(post.date).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
    : '';

  return (
    <div className="min-h-screen bg-surface relative">
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(articleLd) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbLd) }} />
      {faqLd && <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqLd) }} />}
      <div className="fixed inset-0 bg-grid opacity-20 pointer-events-none" />
      <div className="relative z-10 max-w-3xl mx-auto px-4 sm:px-6 py-12">
        {/* Breadcrumb (matches BreadcrumbList schema) */}
        <nav aria-label="Breadcrumb" className="flex items-center gap-2 text-xs text-white/50 mb-6">
          <Link href="/" className="hover:text-white/80 transition">Home</Link>
          <span className="text-white/25">/</span>
          <Link href="/blog" className="hover:text-white/80 transition">Blog</Link>
          <span className="text-white/25">/</span>
          <span className="text-accent-400/80">{post.category}</span>
        </nav>

        <h1 className="text-3xl sm:text-[2.5rem] font-semibold tracking-tight mb-4 text-white/95 leading-[1.15] text-balance">{post.title}</h1>

        {/* Byline — E-E-A-T + freshness + scannability */}
        <div className="flex flex-wrap items-center gap-x-3 gap-y-1 text-xs text-white/50 mb-10">
          {prettyDate && <time dateTime={post.date}>{prettyDate}</time>}
          {prettyDate && <span className="text-white/25" aria-hidden>·</span>}
          <span>{readTime} min read</span>
          <span className="text-white/25" aria-hidden>·</span>
          <span>By SEO Snapshot</span>
        </div>

        {toc.length >= 4 && (
          <nav aria-label="On this page" className="glass-card rounded-xl p-5 mb-10">
            <div className="text-[11px] uppercase tracking-wider text-white/45 mb-3">On this page</div>
            <ol className="space-y-1.5">
              {toc.map((h, i) => (
                <li key={h.id} className="flex gap-2.5 text-sm">
                  <span className="text-white/25 tabular-nums text-xs pt-0.5 w-4 flex-shrink-0">{String(i + 1).padStart(2, '0')}</span>
                  <a href={`#${h.id}`} className="text-white/60 hover:text-accent-300 transition-colors leading-snug">{h.text}</a>
                </li>
              ))}
            </ol>
          </nav>
        )}

        <article className="blog-content" dangerouslySetInnerHTML={{ __html: html }} />

        <div className="mt-12 glass-card rounded-xl p-6 text-center">
          <p className="text-white/60 text-sm mb-3">Check your site&apos;s SEO score for free</p>
          <Link href="/" className="btn-primary text-sm">Analyze your site</Link>
        </div>

        {(refs.checks.length > 0 || refs.terms.length > 0) && (
          <div className="mt-12 grid gap-6 sm:grid-cols-2">
            {refs.checks.length > 0 && (
              <div>
                <h2 className="text-sm font-medium text-white/50 mb-3">Related SEO checks</h2>
                <ul className="space-y-1.5">
                  {refs.checks.map((c) => (
                    <li key={c.slug}>
                      <Link href={`/checks/${c.slug}`} className="text-sm text-accent-400 hover:text-accent-300 transition-colors">
                        {c.title} →
                      </Link>
                    </li>
                  ))}
                </ul>
              </div>
            )}
            {refs.terms.length > 0 && (
              <div>
                <h2 className="text-sm font-medium text-white/50 mb-3">In the SEO glossary</h2>
                <ul className="space-y-1.5">
                  {refs.terms.map((t) => (
                    <li key={t.slug}>
                      <Link href={`/glossary/${t.slug}`} className="text-sm text-accent-400 hover:text-accent-300 transition-colors">
                        {t.term} →
                      </Link>
                    </li>
                  ))}
                </ul>
              </div>
            )}
          </div>
        )}

        {related.length > 0 && (
          <div className="mt-12">
            <h2 className="text-sm font-medium text-white/50 mb-4">Related articles</h2>
            <div className="space-y-3">
              {related.map((r) => (
                <Link key={r.slug} href={`/blog/${r.slug}`}
                  className="flex items-center justify-between gap-3 glass-card rounded-lg px-4 py-3 group hover:border-white/[0.1] transition">
                  <span className="text-sm text-white/70 group-hover:text-accent-400 transition-colors">{r.title}</span>
                  <ArrowRight className="w-3.5 h-3.5 text-white/30 flex-shrink-0" />
                </Link>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
