import { NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';

export async function GET(_req: Request, { params }: { params: { id: string } }) {
  const analysis = await prisma.analysis.findUnique({ where: { id: params.id } });
  if (!analysis) {
    return NextResponse.json({ error: 'Analysis not found' }, { status: 404 });
  }

  const data = JSON.parse(analysis.data);
  const issues = JSON.parse(analysis.issues);

  const domain = new URL(data.url).hostname;
  const date = analysis.createdAt.toISOString().split('T')[0];

  // Generate simple HTML report for PDF conversion
  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>SEO Report - ${domain}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; color: #1a1a2e; padding: 40px; max-width: 800px; margin: 0 auto; }
    .header { text-align: center; margin-bottom: 32px; padding-bottom: 24px; border-bottom: 2px solid #e2e8f0; }
    .header h1 { font-size: 28px; margin-bottom: 8px; }
    .header .url { color: #6366f1; font-size: 16px; }
    .header .date { color: #94a3b8; font-size: 14px; margin-top: 4px; }
    .score-section { text-align: center; margin: 32px 0; }
    .score { font-size: 72px; font-weight: 800; }
    .score.good { color: #22c55e; }
    .score.ok { color: #f59e0b; }
    .score.bad { color: #ef4444; }
    .score-label { font-size: 18px; color: #64748b; margin-top: 8px; }
    .categories { display: grid; grid-template-columns: repeat(2, 1fr); gap: 12px; margin: 24px 0; }
    .cat { background: #f8fafc; border-radius: 8px; padding: 12px 16px; }
    .cat-name { font-size: 13px; color: #64748b; text-transform: uppercase; letter-spacing: 0.5px; }
    .cat-score { font-size: 22px; font-weight: 700; margin-top: 4px; }
    .section { margin: 32px 0; }
    .section h2 { font-size: 20px; margin-bottom: 16px; padding-bottom: 8px; border-bottom: 1px solid #e2e8f0; }
    .issue { padding: 10px 0; border-bottom: 1px solid #f1f5f9; display: flex; gap: 12px; align-items: flex-start; }
    .severity { font-size: 11px; font-weight: 600; padding: 2px 8px; border-radius: 4px; white-space: nowrap; }
    .severity.critical { background: #fef2f2; color: #dc2626; }
    .severity.warning { background: #fffbeb; color: #d97706; }
    .severity.info { background: #eff6ff; color: #2563eb; }
    .issue-text { font-size: 14px; }
    .stats { display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; margin: 24px 0; }
    .stat { text-align: center; }
    .stat-value { font-size: 24px; font-weight: 700; color: #1e293b; }
    .stat-label { font-size: 12px; color: #94a3b8; margin-top: 4px; }
    .footer { text-align: center; margin-top: 40px; padding-top: 24px; border-top: 2px solid #e2e8f0; color: #94a3b8; font-size: 12px; }
  </style>
</head>
<body>
  <div class="header">
    <h1>SEO Snapshot Report</h1>
    <div class="url">${data.url}</div>
    <div class="date">${date}</div>
  </div>

  <div class="score-section">
    <div class="score ${data.score >= 80 ? 'good' : data.score >= 50 ? 'ok' : 'bad'}">${data.score}/100</div>
    <div class="score-label">${data.score >= 80 ? 'Great' : data.score >= 50 ? 'Needs Work' : 'Critical'}</div>
  </div>

  <div class="stats">
    <div class="stat"><div class="stat-value">${data.fetchTime || 0}ms</div><div class="stat-label">Response Time</div></div>
    <div class="stat"><div class="stat-value">${data.wordCount || 0}</div><div class="stat-label">Word Count</div></div>
    <div class="stat"><div class="stat-value">${issues.length}</div><div class="stat-label">Issues Found</div></div>
  </div>

  ${data.categoryScores ? `<div class="categories">
    ${Object.entries(data.categoryScores).map(([name, score]) =>
      `<div class="cat"><div class="cat-name">${name}</div><div class="cat-score">${score}%</div></div>`
    ).join('')}
  </div>` : ''}

  <div class="section">
    <h2>Top Issues (${Math.min(issues.length, 20)} of ${issues.length})</h2>
    ${issues.slice(0, 20).map((issue: any) => `
      <div class="issue">
        <span class="severity ${issue.severity}">${issue.severity}</span>
        <div class="issue-text"><strong>${issue.problem}</strong><br><span style="color:#64748b;font-size:13px">${issue.fix}</span></div>
      </div>
    `).join('')}
  </div>

  <div class="footer">
    Generated by SEO Snapshot &mdash; seosnapshot.dev &mdash; ${date}
  </div>
</body>
</html>`;

  return new Response(html, {
    headers: {
      'Content-Type': 'text/html; charset=utf-8',
      'Content-Disposition': `inline; filename="seo-report-${domain}-${date}.html"`,
    },
  });
}
